from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID
from datetime import datetime
from decimal import Decimal

class ExchangeRate(BaseModel):
    id: Optional[UUID] = Field(default=None, description="Unique ID generated by the DB")
    currency: str = Field(..., description="The currency (e.g. USD, AED, GOLD_G)")
    record_date: datetime = Field(..., description="The date of the exchange rate")
    rate_to_eur: Decimal = Field(..., description="The value in Euros of 1 unit of this currency")

class ExchangeRateCreate(BaseModel):
    currency: str = Field(..., description="The currency (e.g. USD, AED, GOLD_G)")
    record_date: datetime = Field(..., description="The date of the exchange rate")
    rate_to_eur: Decimal = Field(..., description="The value in Euros of 1 unit of this currency")