from pydantic import BaseModel, Field
from decimal import Decimal
from datetime import datetime
from typing import Optional
from uuid import UUID

from src.db.models.enums import OrderSide


class AssetOrder(BaseModel):
    id: UUID = Field(..., description="Unique ID generated by the DB")
    asset_id: UUID = Field(..., description="The asset this order belongs to")
    order_date: datetime = Field(..., description="Order date")
    side: OrderSide = Field(..., description="BUY or SELL")
    quantity: Decimal = Field(..., description="Ordered quantity (positive magnitude)")
    amount_invested: Decimal = Field(..., description="Invested amount (asset currency)")
    fees: Decimal = Field(Decimal("0"), description="Order fees (asset currency)")
    note: Optional[str] = Field(None, description="Free-form note")


class AssetOrderCreate(BaseModel):
    order_date: Optional[datetime] = Field(None, description="Order date; defaults to now")
    side: OrderSide = Field(OrderSide.BUY, description="BUY or SELL")
    quantity: Decimal = Field(..., gt=0, description="Ordered quantity (positive magnitude)")
    amount_invested: Decimal = Field(..., ge=0, description="Invested amount (asset currency)")
    fees: Decimal = Field(Decimal("0"), ge=0, description="Order fees (asset currency)")
    note: Optional[str] = Field(None, description="Free-form note")
