from pydantic import BaseModel, Field
from uuid import UUID
from datetime import datetime
from decimal import Decimal

class AssetPrice(BaseModel):
    id: UUID = Field(..., description="Unique ID generated by the DB")
    asset_id: UUID = Field(..., description="The asset this price belongs to")
    record_date: datetime = Field(..., description="The date of the price")
    price: Decimal = Field(..., description="The recorded price")

class AssetPriceCreate(BaseModel):
    record_date: datetime = Field(..., description="The date of the price")
    price: Decimal = Field(..., description="The recorded price")

class AssetPriceUpdate(BaseModel):
    record_date: datetime = Field(..., description="The date of the price")
    price: Decimal = Field(..., description="The recorded price")
